# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    docker:
      - image: gcc:10.2.0
    steps:
      - checkout
      - run: make util_test
      - run: make Vec3_test
      - run: make Image_test
      - run: make Ray_test